#!/bin/sh

PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin

logger "running /etc/ppp/ip-down script"

. /etc/functions.sh
eval $(/usr/bin/netparam)

# unset default route
ip route del default dev $IFNAME
iptables -t nat -D POSTROUTING -o $IFNAME -j MASQUERADE

if [ "$(nvram get fw_disable)" != "1" ]; then
	iptables -D INPUT -i $IFNAME -m state --state INVALID -j DROP
	iptables -D INPUT -i $IFNAME -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -D INPUT -i $IFNAME -j DROP

	iptables -D OUTPUT -o $IFNAME -j ACCEPT

	iptables -D FORWARD -i $LANDEV -o $IFNAME -m state --state INVALID -j DROP
	iptables -D FORWARD -i $LANDEV -o $IFNAME -s $LANNET/$LANPRE -d ! $LANNET/$LANPRE -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -D FORWARD -i $LANDEV -o $IFNAME -j DROP

	iptables -D FORWARD -i $IFNAME -o $LANDEV -m state --state INVALID -j DROP
	iptables -D FORWARD -i $IFNAME -o $LANDEV -s ! $LANNET/$LANPRE -d $LANNET/$LANPRE -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -D FORWARD -i $IFNAME -o $LANDEV -d $LANNET/$LANPRE -j DROP

	if [ -n "$WIFIADR" ]; then
		iptables -D FORWARD -i $WIFIDEV -o $IFNAME -m state --state INVALID -j DROP
		iptables -D FORWARD -i $WIFIDEV -o $IFNAME -s $WIFINET/$WIFIPRE -d ! $WIFINET/$WIFIPRE -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
		iptables -D FORWARD -i $WIFIDEV -o $IFNAME -j DROP

		iptables -D FORWARD -i $IFNAME -o $WIFIDEV -m state --state INVALID -j DROP
		iptables -D FORWARD -i $IFNAME -o $WIFIDEV -s ! $WIFINET/$WIFIPRE -d $WIFINET/$WIFIPRE -m state --state ESTABLISHED,RELATED -j ACCEPT
		iptables -D FORWARD -i $IFNAME -o $WIFIDEV -d $WIFINET/$WIFIPRE -j DROP
	fi
fi

# PPPoE MTU/MRU issue
iptables -D FORWARD -o $IFNAME -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

# set dns
rm -f /etc/resolv.conf
mv /etc/resolv.conf_ppp /etc/resolv.conf 2>/dev/null

nvram set on_autodns=$(nvram get on_store_autodns)
nvram set wifi_dns=$(nvram get wifi_dns_store)

# restart dhcp-server which forwards dns information
/etc/init.d/S50dnsmasq restart
