CREATE TABLE DUMMYENTITY (ID BIGINT NOT NULL, PAYLOAD VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PERSON (ID BIGINT NOT NULL, LASTNAME VARCHAR(255), STATUS INTEGER, REMARK VARCHAR(255), BANKNAME VARCHAR(255), PSEUDONYM VARCHAR(255), CITY VARCHAR(255), BANKCODE VARCHAR(255), ACCOUNTNUMBER VARCHAR(255), ADDRESS VARCHAR(255), ACCOUNTHOLDER VARCHAR(255), ROLES INTEGER, ZIPCODE VARCHAR(255), EMAIL VARCHAR(255), DATEOFJOINING DATE, FIRSTNAME VARCHAR(255), DISTINGUISHEDNAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
