#!/bin/sh

VALID_KEY=""

for type in rsa dss; do {
  # check for keys
  key=/etc/dropbear/dropbear_${type}_host_key
  [ ! -f $key ] && {
    # generate missing keys
    mkdir -p /etc/dropbear
    [ -x /usr/bin/dropbearkey ] && {
      /usr/bin/dropbearkey -t $type -f $key 2>&- >&- && exec $0 $*
    } &
    exit 0
  }
  [ -f $key ] && VALID_KEY="true"
}; done

if [ $VALID_KEY ]; then
   logger -t S50dropbear Starting dropbear.
   /usr/sbin/dropbear;
else
   logger -p error -t S50dropbear No ssh host key files present, and generation failed on all of them. Falling back to telnetd. THIS IS INSECURE!
   telnetd -l /bin/login;
fi
