#!/bin/sh

for type in rsa dss; do {
  # check for keys
  key=/etc/dropbear/dropbear_${type}_host_key
  [ ! -f $key ] && {
    # generate missing keys
    mkdir -p /etc/dropbear
    [ -x /usr/bin/dropbearkey ] && {
      /usr/bin/dropbearkey -t $type -f $key 2>&- >&- && exec $0 $*
    } &
    exit 0
  }
}; done

if [ -f etc/dropbear/dropbear_dss_host_key ] || [ -f etc/dropbear/dropbear_dss_host_key ]; then
   /usr/sbin/dropbear;
else
   telnetd -l /bin/login;
fi
