#!/bin/sh

echo "  updating nvram variables to opennet defaults.."

# obsolete var, wifi setup now done by opennet-wl ipk
nvram unset wl0_on_init_override

#ssid=$(nvram get wl0_ssid)
#if [ -z $(nvram show 2>/dev/null | grep wl0_on_init_override) ] ; then
#	if [ -z "$ssid" ] || [ $ssid != "olsr.opennet-forum.de" ]; then
#		nvram set wl0_mode=sta
#		nvram set wl0_infra=0
#		nvram set wl0_channel=1
#		nvram set wl0_ssid=olsr.opennet-forum.de
#		nvram set wl0_wds=
#		nvram set wl0_lazywds=0
#		nvram set wl0_wep=on
#		nvram set wl0_wep_bit=128
#		nvram set wl0_key=1
#		nvram set wl0_frag=512
#		nvram set wl0_rts=250
#		nvram set wl0_gmode_protection=auto
#		# deactivate ff dyngw functionality
#		nvram set ff_dyngw=0
#		# disable any wpa-settings
#		nvram set wl_wpa_psk=
#		nvram set wl_wpa_gtk_rekey=
#		nvram set wl0_wpa_gtk_rekey=
#		nvram set wl0_wpa_psk=
#		nvram unset wl0_akm
#		echo " ACHTUNG: WLAN Einstellungen / SSID wurde für opennet angepasst."
#	fi
#fi

if [ -n "$(nvram get lan_ipaddr | grep ^192.168)" ]; then
	nvram set lan_ipaddr=172.16.0.1
	nvram set lan_netmask=255.255.255.0
	nvram set lan_proto=static
	echo "  - changed lan interface => ip 172.16.0.1, mask 255.255.255.0"
fi

WIFIDEV="$(awk '$1 ~ ":$" {gsub(":",""); print $1; exit} ' /proc/net/wireless)"
if [ -z $(nvram get wifi_ifname) ]; then
	nvram set wifi_ipaddr=192.168.33.127
	nvram set wifi_netmask=255.255.0.0
	nvram set wifi_proto=static
	nvram set wifi_ifname=$WIFIDEV
	echo "  - changed wifi interface => ip 192.168.33.127, mask 255.255.0.0"
fi

if [ -z $(nvram get wl0_ifname) ]; then
        nvram set wl0_ifname=$WIFIDEV
fi

# remove wifi device from list of bridged devices
ifnames=
for if in $(nvram get lan_ifnames); do
	if [ "$if" != "$WIFIDEV" ]; then
		ifnames="$ifnames $if"
	fi
done
ifnames=$(echo $ifnames)
nvram set lan_ifnames="$ifnames"

# especially on asus dhcp_start is by default not set to an integer value, so fix this
nvram set dhcp_start=100
nvram set dhcp_num=50

# activate automatic olsrd configuration
on_remoteconf=$(nvram get on_remoteconf)
if [ -z "$on_remoteconf" ]; then
	nvram set on_remoteconf="on"
	echo "  - changed remoteconf => on (used for olsr configuration)"
fi

# limit txpwr, assume always a external Antenna
on_ant_dbi=$(nvram get on_ant_dbi)
ff_txpwr=$(nvram get ff_txpwr)
if [ -z "$on_ant_dbi" ]; then
	nvram set on_ant_dbi=8
fi
if [ -z "$ff_txpwr" ]; then
	nvram set ff_txpwr=15
	echo "  - changed wifi txpwr => 15 mW
fi

# activate automatic optimization of txpwr by default if not deactivated
on_autoadapttxpwr=$(nvram get on_autoadapttxpwr)
if [ -z "$on_autoadapttxpwr" ]; then
	nvram set on_autoadapttxpwr=on
	echo "  - changed wifi optimization => auto-adapt txpwr"
fi

# if the list of possible gateways is empty switch auto-search on
on_gwaddrs=$(nvram get on_gwaddrs)
if [ -z "$on_gwaddrs" ]; then
	nvram set on_gwauto=on
	echo "  - changed gateway selection => auto-search mode"
fi

# activate automatic selection of DNS-Servers by default
if [ -z "$(nvram show 2>/dev/null | grep on_autodns)" ]; then
	nvram set on_autodns=on
	echo "  - changed dns server detection => auto-search mode"
fi

# set user-gateway default (need more work later!)
on_ugw=$(nvram get on_ugw)
if [ -z "$on_ugw" ]; then
	nvram set on_ugw="nagare.on-i.de"
	echo "  - changed user-gateway => nagare.on-i.de"
fi

# always set boot_wait
nvram set boot_wait=on

# set wan_device to former wan_ifname or pppoe_ifname
if [ -z "$(nvram get wan_device)" ]; then
	wan_ifname="$(nvram get wan_ifname)"
	if [ "$wan_ifname" != "ppp0" ]; then
		nvram set wan_device="$wan_ifname";
	else
		nvram set wan_device="$(nvram get pppoe_ifname)";
	fi;
fi

# set firmware-version to nvram variables
_version=$( grep "(" /etc/banner )
_version="${_version%% ---*}"
nvram set on_fw_version="$(echo $_version)"
nvram set on_fw_pkgversion="0.11ipkg-9"

### switch from openwrt to opennet-specific ############################

rm -f /etc/banner; cp /rom/etc/banner /etc/banner; 
echo " -- modified with opennet-firmware 0.11ipkg-9 ------ " >>/etc/banner
echo " --------------------------------------------------- " >>/etc/banner

awk '!/Opennet-Interface/ {print}' /www/cgi-bin/webif/.categories >/www/cgi-bin/webif/.categories_bak
rm /www/cgi-bin/webif/.categories
cp /www/cgi-bin/webif/.categories_bak /www/cgi-bin/webif/.categories

echo "##WEBIF:category:Opennet-Interface" >>/www/cgi-bin/webif/.categories

### bugfixes section (repairing of old bugs) ###########################

if [ -e /www/cgi-bin/webif/upgrade.sh_on ]; then
	cd /www/cgi-bin/webif/
	upgrade_sh_on_md5=$(md5sum upgrade.sh_on 2>/dev/null| cut -d" " -f1)
	upgrade_sh_bak_md5=$(md5sum upgrade.sh_bak 2>/dev/null| cut -d" " -f1)
	if [ -e upgrade.sh_bak ] && [ "$upgrade_sh_on_md5" = "$upgrade_sh_bak_md5" ]; then
			echo "  - repairing broken (but hidden) firmware-update interface"
			ln -sf /rom/www/cgi-bin/webif/upgrade.sh upgrade.sh_bak
	elif [ -e upgrade.sh ] && [ "$upgrade_sh_on_md5" = "$upgrade_sh_bak_md5" ]; then
			echo "  - repairing broken firmware-update interface"
			ln -sf /rom/www/cgi-bin/webif/upgrade.sh .
	fi
fi

rm -f /usr/sbin/check_nagare.sh

rm -f /www/cgi-bin/18-localaccess
rm -f /www/cgi-bin/on_localaccess.html
rm -f /etc/init.d/S83wifiaccess
nvram unset on_wldhcp_num
nvram unset on_wldhcp
nvram unset on_wldhcp_start
nvram unset on_wldhcp_lease
nvram unset dhcpwl_proto
nvram unset dhcpwl_ipaddr
nvram unset dhcpwl_ifname
nvram unset dhcpwl_netmask
nvram unset on_wifi_access

if [ -n "$(nvram get on_wifiaccess_route_override)" ]; then
	nvram set on_wifidhcp_route_override=$(nvram get on_wifiaccess_route_override)
	nvram unset on_wifiaccess_route_override
fi

if [ -e /etc/openvpn/on_aps.key ]; then
	mv -f /etc/openvpn/on_aps.key /etc/openvpn/opennet_user/
fi
if [ -e /etc/openvpn/on_aps.crt ]; then
	mv -f /etc/openvpn/on_aps.crt /etc/openvpn/opennet_user/
fi
if [ -e /etc/openvpn/on_aps.csr ]; then
	mv -f /etc/openvpn/on_aps.csr /etc/openvpn/opennet_user/
fi


if [ -e /etc/openvpn/opennet_dsl ]; then
	if [ -e /etc/openvpn/opennet_dsl/on_ugws.key ]; then
		mv -f /etc/openvpn/opennet_dsl/on_ugws.key /etc/openvpn/opennet_ugw/on_ugws.key
	fi
	if [ -e /etc/openvpn/opennet_dsl/on_ugws.crt ]; then
		mv -f /etc/openvpn/opennet_dsl/on_ugws.crt /etc/openvpn/opennet_ugw/on_ugws.crt
	fi
	if [ -e /etc/openvpn/opennet_dsl/on_ugws.csr ]; then
		mv -f /etc/openvpn/opennet_dsl/on_ugws.csr /etc/openvpn/opennet_ugw/on_ugws.csr
	fi
	rm -rf /etc/openvpn/opennet_dsl
fi

if [ -z "$(nvram get on_share_internet)" ]; then
	nvram set on_share_internet=$(nvram get on_sharedsl)
fi
nvram unset on_sharedsl
nvram unset on_sharedsl_blocked

########################################################################
	
# wenn key's auf dem AP, blockiere OpenWrt-Interface zum firmware-update
if ! [ -e upgrade.sh_bak ] && [ -f /etc/openvpn/opennet_user/on_aps.key ] || [ -f /etc/openvpn/opennet_ugw/on_ugws.key ]; then
	mv -f /www/cgi-bin/webif/upgrade.sh /www/cgi-bin/webif/upgrade.sh_bak 2>/dev/null
	ln -s /www/cgi-bin/webif/upgrade.sh_on /www/cgi-bin/webif/upgrade.sh 2>/dev/null
fi

nvram commit

echo "  ..done."

echo "  ################################################### "
echo "  #         please reboot after installation        # "
echo "  #      bitte AP nach Installation neu starten     # "
echo "  #  (warte bis Meldung 'Successfully terminated')  # "
echo "  ################################################### "
