#!/bin/sh
echo "  removing files to replace"

rm -f /bin/login

rm -f /etc/init.d/S40network
rm -f /etc/init.d/S45firewall
rm -f /etc/init.d/S50telnet
rm -f /etc/init.d/S50httpd
rm -f /etc/init.d/S50dropbear
rm -f /etc/init.d/S50dnsmasq
rm -f /etc/init.d/S60cron
rm -f /etc/init.d/S60olsrd

rm -f /etc/olsrd.conf

rm -f /etc/ssl/openssl.cnf

rm -f /www/index.html

rm -f /etc/ppp/ip-up
rm -f /etc/ppp/ip-down

# restoring Webinterface (be)for firmware-update/upgrade
mv -f /www/cgi-bin/webif/upgrade.sh_bak /www/cgi-bin/webif/upgrade.sh 2>/dev/null
mv -f /www/cgi-bin/webif/.categories_bak /www/cgi-bin/webif/.categories

echo "  removing files to replace - done"
