#!/bin/sh
# hack to clear the problem with the ses-button on Buffalo WHR-G54S
# same like on Buffalo WHR-HP-G54
# see: https://dev.openwrt.org/ticket/1143
# see: https://dev.openwrt.org/changeset/5687

case "$(cat /proc/diag/model)" in
	"Buffalo WHR-G54S")
	echo 0x4000 > /proc/diag/gpiomask
	logger -t /etc/hotplug.d/button/01-gpiomask "hack to switch off Buffalo WHR-G54S ses-button"
	;;
	"Buffalo WHR-G54")
	echo 0x4000 > /proc/diag/gpiomask
	logger -t /etc/hotplug.d/button/01-gpiomask "hack to switch off Buffalo WHR-G54 ses-button"
	;;
	"Buffalo WHR-HP-G54")
	echo 0x4000 > /proc/diag/gpiomask
	logger -t /etc/hotplug.d/button/01-gpiomask "hack to switch off Buffalo WHR-HP-G54 ses-button"
	;;
esac
