#!/bin/sh

while true; do
	gw_addrs="$(/usr/sbin/working_gateways.sh) pool.ntp.org";
	for gw_addr in $gw_addrs; do
		echo "trying $gw_addr"
		ping -c 1 $gw_addr >/dev/null 2>/dev/null &&  [ -n "$(/usr/sbin/ntpclient -s -c 3 -i 5 -g 1000000 -h  $gw_addr)" ] && return;
	done;
	# if this is the first time the accesspoint is started after a firmware-flash, dont try this forever
	# this is important to get 'firstboot' called by /etc/init.d/S99done also if there is no timeserver available.
	[ -z "$(awk '/jffs2/ {print $2}' /proc/mounts)" ] && return
	sleep 3;
done;
