#!/bin/sh

test "0" = "$(nvram get ff_dnsmasq)" && exit

. /etc/functions.sh

test -d /var/etc || mkdir -p /var/etc # create directory if not found
test -d /var/run || mkdir -p /var/run # create directory if not found

write_config()
{
	cat>/var/etc/dnsmasq.conf<<EOF
# filter what we send upstream
bogus-priv
filterwin2k

# allow /etc/hosts and dhcp lookups via *.lan
addn-hosts=/etc/local.hosts
expand-hosts

EOF

	if [ -z "$WANOLSR" ]; then
		cat>>/var/etc/dnsmasq.conf<<EOF
# no dns queries from the wan
except-interface=vlan1

EOF
	fi

	DHCPEND=$(nvram get dhcp_num)
	test -z "$DHCPEND" && DHCPEND=4
	if [ $DHCPEND -gt 0 ]; then
		DHCPLEASE=$(nvram get dhcp_lease)
		test -z "$DHCPLEASE" && DHCPLEASE=12h
		test "$DHCPLEASE" = "0" && DHCPLEASE=12h
		DHCPNET=$(echo $LANNET|cut -d'.' -f1-3)
		DHCPBEG=$(nvram get dhcp_start)
		DHCPBEG=${DHCPBEG##*.}
		test -z "$DHCPBEG" && DHCPBEG=100
		DHCPEND=$(( $DHCPBEG + $DHCPEND - 1 ))
		echo "dhcp-range=wired,$DHCPNET.$DHCPBEG,$DHCPNET.$DHCPEND,$LANMSK,$DHCPLEASE">>/var/etc/dnsmasq.conf
	fi

#### changed the fields to more descriptive
#	WLDHCP=$(nvram get ff_wldhcp)
#	IFS=\;
#	for ENT in $WLDHCP; do
#		NET=${ENT%[:,]*}
#		MSK=${ENT#*[:,]}
#		if [ -n "$NET" ] && [ -n "$MSK" ]; then
#			DHCPLEASE=2h
#			DHCPBEG=$(ipcalc $NET|grep "NETWORK"|cut -d'.' -f4)
#			DHCPBEG=$(( $DHCPBEG + 2 ))
#			DHCPEND=$(ipcalc $NET|grep "BROADCAST"|cut -d'.' -f4)
#			DHCPEND=$(( $DHCPEND - 1 ))
#			DHCPNET=$(ipcalc $NET|grep "NETWORK"|cut -d'=' -f2|cut -d'.' -f1-3)
#			echo "dhcp-range=wlnat,$DHCPNET.$DHCPBEG,$DHCPNET.$DHCPEND,$MSK,$DHCPLEASE">>/var/etc/dnsmasq.conf
#		fi
#	done

	WLDHCP=$(nvram get on_wldhcp)
	WLDHCPEND=$(nvram get on_wldhcp_num)
	test -z "$WLDHCPEND" && WLDHCPEND=4
	if [ "$WLDHCP" = "on" ] && [ $WLDHCPEND -gt 0 ]; then
		WLDHCPLEASE=$(nvram get on_wldhcp_lease)
		test -z "$WLDHCPLEASE" && WLDHCPLEASE=12h
		test "$WLDHCPLEASE" = "0" && WLDHCPLEASE=12h
		
		# changed the net to separate it from AP adresses
		# WLDHCPNET=$(echo $DHCPWIFINET|cut -d'.' -f1-3)
		WLDHCPNET=$(echo $DHCPWIFINET|cut -d'.' -f1-2)"."$(($(echo $DHCPWIFINET|cut -d'.' -f3)+1))
		WLDHCPBEG=$(nvram get on_wldhcp_start)
		WLDHCPBEG=${WLDHCPBEG##*.}
		test -z "$WLDHCPBEG" && WLDHCPBEG=100
		WLDHCPEND=$(( $WLDHCPBEG + $WLDHCPEND - 1 ))
		echo "dhcp-range=wlnat,$WLDHCPNET.$WLDHCPBEG,$WLDHCPNET.$WLDHCPEND,$WIFIMSK,$WLDHCPLEASE">>/var/etc/dnsmasq.conf
		
		echo "dhcp-option=wlnat,1,$DHCPWIFIMSK" >>/var/etc/dnsmasq.conf
		echo "dhcp-option=wlnat,3,$DHCPWIFIADR" >>/var/etc/dnsmasq.conf
		
		# use the defined dns-addresses as resolver
		dnsaddrs=$(nvram get lan_dns | awk 'gsub(" ",",")')
		test -z "$dnsaddrs" && dnsaddrs=",195.50.140.250"
		echo "dhcp-option=wlnat,6,$dnsaddrs" >>/var/etc/dnsmasq.conf
	fi

	cat>>/var/etc/dnsmasq.conf<<EOF
dhcp-leasefile=/var/run/dhcp.leases

# allow a /etc/ethers for static hosts
read-ethers

                                                                                

# other useful options:
#      subnet mask: dhcp-option=wired,1,255.255.255.0
# default route(s): dhcp-option=wired,3,192.168.1.1,192.168.1.2
#    dns server(s): dhcp-option=wired,6,192.168.1.1,192.168.1.2
#   broadcast addr: dhcp-option=wired,28,192.168.1.255
#   broadcast addr: dhcp-option=wlnat,28,172.31.255.255
EOF

	test -f /etc/local.dnsmasq.conf && cat>>/var/etc/dnsmasq.conf</etc/local.dnsmasq.conf
}

case $1 in
	start)
		echo "Starting dnsmasq..."
		export NVRAM_wan_ifname
		export NVRAM_lan_ifname
		export NVRAM_lan_ifnames
		eval $(/usr/bin/netparam)
		write_config

		rm -f /var/etc/resolv.conf
		echo "nameserver 127.0.0.1">>/var/etc/resolv.conf
		# Compatibility with openwrt
		ln -sf /var/etc/resolv.conf /tmp/resolv.conf

		/usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf
	;;
	stop)
		echo "Stopping dnsmasq..."
		killall dnsmasq
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 start|stop|restart"
	;;
esac
