#!/bin/sh

# remove old dns-entries,
# they will be created again by ifup or by cron.minutely_ongateway
rm -f /etc/resolv.conf

if [ -n "$(nvram get on_store_autodns)" ]; then
	nvram set on_autodns="$(nvram get on_store_autodns)"
	nvram unset on_store_autodns
fi
	
if [ -n "$(nvram get lan_dns_store)" ]; then
	nvram set lan_dns="$(nvram get lan_dns_store)"
	nvram unset lan_dns_store
fi

if [ "$(nvram get on_autodns)" = "on" ]; then
	# use the two first gateways as possible dns-servers
	gw_addrs=$(/usr/sbin/working_gateways.sh)
	dnsaddrs=
	for gw_addr in $gw_addrs; do
		if [ -z "$dnsaddrs" ]; then
			dnsaddrs=$gw_addr;
		else
			nvram set lan_dns="$dnsaddrs $gw_addr"; break;
		fi
	done
fi