#!/bin/sh

# arp-table might be to small in some cases, so give the arp-table more RAM
# see http://forum.openwrt.org/viewtopic.php?pid=14277
echo 1024 > /proc/sys/net/ipv4/neigh/default/gc_thresh1
echo 2048 > /proc/sys/net/ipv4/neigh/default/gc_thresh2
echo 4096 > /proc/sys/net/ipv4/neigh/default/gc_thresh3

case "$1" in
  start|restart)
    ifup lan
    ifup wifi
    wifi up

    if [ -z $(nvram get on_wifiaccess_route_override) ] && [ "$(nvram get wifi_ipaddr | cut -d'.' -f3)" != "33" ]; then
	nvram set dhcpwl_ifname="$(nvram get wifi_ifname):0"
	nvram set dhcpwl_ipaddr="192.168.34.$(nvram get wifi_ipaddr | cut -d'.' -f4)"
	nvram set dhcpwl_netmask="255.255.254.0"
	nvram set dhcpwl_proto=static
	ifup dhcpwl
    fi
    
    # bring up wan as the latest device to have all other device-parameters for calling ip-up
    ifup wan
    
    for route in $(nvram get static_route); do {
      eval "set $(echo $route | sed 's/:/ /g')"
      $DEBUG route add -net $1 netmask $2 gw $3 metric $4 dev $5
    } done
    ;;
esac
