#!/bin/sh
if test -z "$FAILSAFE"; then
	test -d /var/etc || mkdir -p /var/etc
	ff_pw=$(grep '^root:' /etc/passwd | cut -d: -f2)
	test -n "$ff_pw" || ff_pw=admin
	cat > /var/etc/httpd.conf <<EOM
A:*
.asp:text/html
/cgi-bin:root:$ff_pw 
/cgi-bin:admin:$ff_pw 
.svg:image/svg+xml          
.png:image/png    
.gif:image/gif
.jpg:image/jpg
EOM
	/usr/sbin/httpd -c /var/etc/httpd.conf -p 80 -h /www -r "Opennet Webadmin, Log in as root"
else
	cat > /var/etc/httpd.conf <<EOM
A:*
.asp:text/html
.svg:image/svg+xml          
.png:image/png    
.gif:image/gif
.jpg:image/jpg
EOM
	/usr/sbin/httpd -c /var/etc/httpd.conf -p 80 -h /www -r "Opennet Webadmin, FAILSAFE"
fi
# make olsrd.conf visible
ln -sf /var/etc/olsrd.conf /www/olsrd.conf
