#!/bin/sh

test -n "$FAILSAFE" && exit

. /etc/functions.sh

case $1 in
	start)
		echo "Starting batmand..."
		if [ ! -x /usr/sbin/batmand ]; then echo "batmand not installed"; exit; fi;
		if [ "$(nvram get on_batman)" != "true" ]; then echo "batmand not activated"; exit; fi;
		BATMANDEVS=$(nvram get on_bat_ifname)
		ifconfig tap0 >/dev/null 2>/dev/null
		if [ $? = 0 ]; then BATMANDEVS=$BATMANDEVS" tap0"; fi
		ifconfig tap1 >/dev/null 2>/dev/null
		if [ $? = 0 ]; then BATMANDEVS=$BATMANDEVS" tap1"; fi
		batmand $BATMANDEVS
	;;
	stop)
		echo "Stopping batmand if running..."
		killall batmand >/dev/null 2>&1
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 start|stop|restart"
	;;
esac
