#!/bin/sh

PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin

logger "running /etc/ppp/ip-up script"

. /etc/functions.sh
eval $(/usr/bin/netparam)

# set default route
ip route add default via $IPREMOTE dev $IFNAME
iptables -t nat -A POSTROUTING -o $IFNAME -j MASQUERADE

if [ "$(nvram get fw_disable)" != "1" ]; then
	iptables -I INPUT -i $IFNAME -j DROP
	iptables -I INPUT -i $IFNAME -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -I INPUT -i $IFNAME -m state --state INVALID -j DROP

	iptables -I OUTPUT -o $IFNAME -j ACCEPT

	iptables -I FORWARD -i $LANDEV -o $IFNAME -j DROP
	iptables -I FORWARD -i $LANDEV -o $IFNAME -s $LANNET/$LANPRE -d ! $LANNET/$LANPRE -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
	iptables -I FORWARD -i $LANDEV -o $IFNAME -m state --state INVALID -j DROP

	iptables -I FORWARD -i $IFNAME -o $LANDEV -d $LANNET/$LANPRE -j DROP
	iptables -I FORWARD -i $IFNAME -o $LANDEV -s ! $LANNET/$LANPRE -d $LANNET/$LANPRE -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -I FORWARD -i $IFNAME -o $LANDEV -m state --state INVALID -j DROP

	if [ -n "$WIFIADR" ]; then
		iptables -I FORWARD -i $WIFIDEV -o $IFNAME -j DROP
		iptables -I FORWARD -i $WIFIDEV -o $IFNAME -s $WIFINET/$WIFIPRE -d ! $WIFINET/$WIFIPRE -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
		iptables -I FORWARD -i $WIFIDEV -o $IFNAME -m state --state INVALID -j DROP

		iptables -I FORWARD -i $IFNAME -o $WIFIDEV -d $WIFINET/$WIFIPRE -j DROP
		iptables -I FORWARD -i $IFNAME -o $WIFIDEV -s ! $WIFINET/$WIFIPRE -d $WIFINET/$WIFIPRE -m state --state ESTABLISHED,RELATED -j ACCEPT
		iptables -I FORWARD -i $IFNAME -o $WIFIDEV -m state --state INVALID -j DROP
	fi
fi

# PPPoE MTU/MRU issue
iptables -I FORWARD -o $IFNAME -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu


# set dns
nvram set wifi_dns_store=$(nvram get wifi_dns)
nvram set wifi_dns="$DNS1 $DNS2"
nvram set on_store_autodns=$(nvram get on_autodns)
nvram set on_autodns="off"

mv /etc/resolv.conf /etc/resolv.conf_ppp 2>/dev/null

echo "nameserver $DNS1" >/etc/resolv.conf
echo "nameserver $DNS2" >>/etc/resolv.conf

# restart dhcp-server which forwards dns information
/etc/init.d/S50dnsmasq restart
